name: indivfound
channels:
  - defaults
dependencies:
  - python=3.11.5
  - torchvision=0.16.1
  - pytorch-cuda=12.1
  - torchaudio=2.1.1
  - pandas=2.2.3
  - scipy=1.11.3
  - tensorflow==2.15.0.post1
  - ipykernel==6.29.3
