dataset_list:
  [ 'AMIGOS', 'BioVid','DREAMER','SEED_VIG' ,'SEED']

dataset_csv_path:
  [
      '/home/user4/data/ICFound-Data/temporal/anno/AMIGOS_updated.csv',
      '/home/user4/data/ICFound-Data/temporal/anno/BioVid.csv',
      '/home/user4/data/ICFound-Data/temporal/anno/DREAMER.csv',
      '/home/user4/data/ICFound-Data/temporal/anno/SEED-VIG.csv',
      '/home/user4/data/ICFound-Data/temporal/anno/SEED.csv'
  ]

temp: 0.1

video:
  width: 224
  height: 224
  length: 32
  channel: 3
  tubelet_size: 2
  patch_size: 16

eeg:
  eeg_width: 9
  eeg_height: 9
  eeg_length: 6000
  eeg_channel: 1
  eeg_tubelet_size: 200
  eeg_patch_size: 1

ecg:
  ecg_length: 3840
  ecg_channel: 2
  ecg_tubelet_size: 128

eog:
  eog_length: 3840
  eog_channel: 2
  eog_tubelet_size: 128

emg:
  emg_length: 3840
  emg_channel: 3
  emg_tubelet_size: 128

gsr:
  gsr_length: 3840
  gsr_channel: 1
  gsr_tubelet_size: 128

encoder:
  embed_dim: 768
  encoder_depth: 12
  modality_specific_depth: 8
  num_heads: 12

decoder:
  decoder_embed_dim: 512
  decoder_depth: 4
  decoder_num_heads: 16

mlp_ratio: 4.
norm_layer: nn.LayerNorm
tr_pos: False

model_save_root: "/home/user4/program/IndivFound/saved_models/pretrain"
epochs: 200
save_interval: 5
lr: 0.00005
oprim: "adam"
warmup: False
lr_start: 10
lr_step: 20
lr_decay: 0.5
n_print_steps: 100
norm_pix_loss: False
lr_adapt: True
lr_patience: 2

batch_size: 48
num_workers: 8

mask_ratio_video: 0.75
mask_ratio_eeg: 0.5
mask_ratio_ecg: 0.5
mask_ratio_eog: 0.5
mask_ratio_emg: 0.5
mask_ratio_gsr: 0.5

